// Voltage Monitoring 
// MCU: STM32C031K6T6
// Sensor: ZMPT101B
// Author: Spencer Grow

#include <stdio.h>
#include <math.h>
//#include "main.h"
#include "generator.h"

//global vars
ADC_HandleTypeDef hadc1;     // Handle for the ADC hardware (ADC1)
float voltage_rms = 0.0f;    // Stores last measured RMS voltage (in volts)
float mains_threshold = 80.0f; // Voltage threshold (below this = power failure)

//Pin assignments for SSR
GPIO_TypeDef* SSR_PORT = GPIOA;
uint16_t MAIN_SSR_PIN   = GPIO_PIN_1;
uint16_t BACKUP_SSR_PIN = GPIO_PIN_2;

//Function Prototypes
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_ADC1_Init(void);
float Read_Voltage_RMS(void);

//main
int main(void){

    HAL_Init(); //initalize HAL
    SystemClock_Config();     // Configure system clock (auto-generated by CubeIDE)
    MX_GPIO_Init();           // Initialize GPIO pins (for SSR control)
    MX_ADC1_Init();           // Initialize ADC1 (for voltage sensor)

    while (1)
    {
        // Step 1: Measure AC RMS voltage from ZMPT101B
        voltage_rms = Read_Voltage_RMS();

        // Step 2: Compare voltage to threshold to decide power state
        if (voltage_rms < mains_threshold)
        {
            //Power failure detected
            HAL_GPIO_WritePin(SSR_PORT, MAIN_SSR_PIN, GPIO_PIN_RESET); // Turn OFF main SSR

            // Step 3: Run generator startup simulation
            generator_startup_sequence();  // This runs choke -> start -> run

            // Step 4: Turn ON backup SSR only after generator is "ready"
            HAL_GPIO_WritePin(SSR_PORT, BACKUP_SSR_PIN, GPIO_PIN_SET);
        }
        else
        {
            // Main power normal

            HAL_GPIO_WritePin(SSR_PORT, MAIN_SSR_PIN, GPIO_PIN_SET);   // Turn ON main SSR
            HAL_GPIO_WritePin(SSR_PORT, BACKUP_SSR_PIN, GPIO_PIN_RESET); // Turn OFF backup SSR

            // Stop generator simulation
            generator_stop();
        }

        HAL_Delay(500); // Wait 0.5s before checking again
    }
}

// RMS Voltage Reading



//Peripheral init



