// Voltage Monitoring 
// MCU: STM32C031K6T6
// Sensor: ZMPT101B
// Author: Spencer Grow

#include <stdio.h>
#include <math.h>
//#include "stm32c0xx_hal.h"
#include "generator.h"
#include "Display.h"

//thresholds
float low_voltage  = 86.0f;   // Vrms minimum AC
float high_voltage = 128.0f;  // Vrms maximum AC

//GPIO assignments
#define RELAY_PORT GPIOA

// SSR / SPDT
#define MAIN_SSR_PIN   GPIO_PIN_1
#define BACKUP_SSR_PIN GPIO_PIN_2
#define SPDT_PIN       GPIO_PIN_6

// Generator step LEDs
#define CHOKE_LED_PIN  GPIO_PIN_3
#define START_LED_PIN  GPIO_PIN_4
#define RUN_LED_PIN    GPIO_PIN_5

// Safety delay before switching SPDT (ms)
#define SAFETY_DELAY_MS 300

//Function Prototypes
ADC_HandleTypeDef hadc1;
float Read_Voltage_RMS(void);

typedef enum {
    SOURCE_MAIN,
    SOURCE_BACKUP
} PowerSource;

PowerSource current_source = SOURCE_MAIN; // assume main AC on startup


//main
int main(void){

    HAL_Init(); //initalize HAL
    SystemClock_Config();     // Configure system clock (auto-generated by CubeIDE)
    MX_GPIO_Init();           // Initialize GPIO pins (for SSR control)
    MX_ADC1_Init();           // Initialize ADC1 (for voltage sensor)
    display_init();           // 7-segment display for voltage readings

    while (1)
    {
        float voltage = Read_Voltage_RMS();

        // Update 7-segment display
        display_voltage(voltage);

        if (voltage >= low_voltage && voltage <= high_voltage)
        {
            // Check if on backup
            if (current_source != SOURCE_MAIN)
            {
                //Switch from backup to main
                HAL_GPIO_WritePin(RELAY_PORT, BACKUP_SSR_PIN, GPIO_PIN_RESET); // turn off backup SSR
                generator_stop();  // stop generator
                HAL_Delay(SAFETY_DELAY_MS); // safety delay before SPDT

                HAL_GPIO_WritePin(RELAY_PORT, SPDT_PIN, GPIO_PIN_RESET);       // SPDT switches to main
                HAL_GPIO_WritePin(RELAY_PORT, MAIN_SSR_PIN, GPIO_PIN_SET);     // turn on main SSR

                current_source = SOURCE_MAIN; // update current source
            }
            // else: already on main, do nothing
        }
        else
        {
            // Check if on main source
            if (current_source != SOURCE_BACKUP)
            {
                //Switch from main to backup
                HAL_GPIO_WritePin(RELAY_PORT, MAIN_SSR_PIN, GPIO_PIN_RESET);   // turn off main SSR
                generator_startup_sequence();                                   // start generator sequence
                HAL_Delay(SAFETY_DELAY_MS);                                     // safety delay before SPDT

                HAL_GPIO_WritePin(RELAY_PORT, SPDT_PIN, GPIO_PIN_SET);         // SPDT switches to backup
                HAL_GPIO_WritePin(RELAY_PORT, BACKUP_SSR_PIN, GPIO_PIN_SET);   // turn on backup SSR

                current_source = SOURCE_BACKUP; // update current source
            }
            // else: already on backup, do nothing
        }

        HAL_Delay(200); // main loop delay
    }
}

// RMS Voltage Reading
float Read_Voltage_RMS(void)
{
    const uint16_t samples = 200;         // Number of ADC samples per measurement
    const float ADC_MID = 2048.0f;        // Midpoint of 12-bit ADC (3.3V reference)
    uint32_t sum_sq = 0;

    for (uint16_t i = 0; i < samples; i++)
    {
        HAL_ADC_Start(&hadc1);
        HAL_ADC_PollForConversion(&hadc1, HAL_MAX_DELAY);
        uint16_t adc_val = HAL_ADC_GetValue(&hadc1);
        HAL_ADC_Stop(&hadc1);

        float centered = (float)adc_val - ADC_MID;  // Remove DC bias
        sum_sq += centered * centered;
    }

    // Compute RMS in ADC units
    float adc_rms = sqrtf((float)sum_sq / samples);

    // Convert to volts (Vref = 3.3V)
    float sensor_voltage = (adc_rms / ADC_MID) * 1.65f; // 1.65 V = midpoint bias

    // Apply calibration factor (depends on ZMPT101B transformer & divider)
    float voltage_rms = sensor_voltage * 100.0f; // Example: scale to 0–125V AC RMS

    return voltage_rms;
}



//Peripheral init

//GPIO_init for SSRs 

//ADC_init for voltage monitoring

